### ISSUE TITLE
question: in which jurisdiction is hosted the default Firefox Sync server?

### ISSUE THREAD

**Issue by monperrus** [mozilla-services/syncserver#171]
I'm concerned about privacy.

In which jurisdiction / data center is hosted the default Firefox sync server `https://token.services.mozilla.com/1.0/sync/1.5`?

**Comment by thomcc** [comment]
I don't know the answer to this question (to a certain extent I believe it depends where you are located -- there are many servers), but all user data is fully encrypted before it is sent to the server, with a key that always remains on your machine, so even if the answer is in a location you find unfavorable, it shouldn't make too large of a difference.

https://hacks.mozilla.org/2018/11/firefox-sync-privacy/ discusses how the system is designed. It's very privacy-focused.

**Comment by monperrus** [comment]
Thanks for your answer. Indeed it's very privacy-focused.

The jurisdiction of the server is also an aspect of privacy.

It is important to know the jurisdiction to understand whether the NSA or any surveillance service can force Mozilla to provide the Sync data (even encrypted) or to introduce a backdoor.

**Comment by rfk** [comment]
I'm not a lawyer, and I recommend consulting Mozilla's various [legal docs](https://www.mozilla.org/en-US/about/legal/) for more info. But I can offer the following:

* The servers are currently hosted in Amazon Web Services in the US. This is an implementation detail and we don't commit to hosting (or to not hosting) in any particular jurisdiction in the future.
* The servers are operated by Mozilla Corporation, which is headquartered in the US.

Github is not a great place for further conversation on this front, so I'm going to close the issue here.  If the above legal docs do not sufficiently answer your questions, I recommend reaching out via one of the "contact us" links on those pages, to get connected to the right folks to answer detailed legal questions.

**Comment by monperrus** [comment]
Thanks a lot Ryan, this is the precise answer to the original question.
