### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by vmunix** [mozilla-services/syncserver#24]
A nice to have would be an up to date Docker image to make deployment and testing easier. Perhaps also an AMI? Maybe we should look at http://www.packer.io/ or something for this kind of thing.

**Comment by nrobinaubertin** [comment]
Hi,
I just recently saw that there is a mozilla/syncserver docker image. I made my own a while ago and it's significantly smaller since it's base on alpine linux (97.2MB vs 244MB).
I wanted to share it if anyone is interested, so there it is: https://github.com/nrobinaubertin/dockerfiles/tree/master/firefox_syncserver
