### ISSUE TITLE
Sandstorm App

### ISSUE THREAD

**Issue by julianpistorius** [mozilla-services/syncserver#72]
I'd love to be able to install this from the Sandstorm marketplace (https://apps.sandstorm.io/). What would be involved?

See here for a discussion:

https://groups.google.com/forum/#!searchin/sandstorm-app-committee/firefox/sandstorm-app-committee/udhzBjIc_HI/HsTOBfSptyMJ

**Comment by rfk** [comment]
I haven't looked into sandstorm in a while, but from what I remember, it wants to be in control of the authentication piece for all the apps.  I think it will be hard to make that work with the way Firefox Accounts auth works in Firefox.

I won't have any bandwidth to dedicate to actually hacking trying it out, but if you're interested in trying, I'm happy to offer advice on any specific stumbling blocks you run into.

**Comment by kentonv** [comment]
For the record, Sandstorm would require that API requests (from Firefox, presumably) arrive over HTTPS and are authenticated either using:

1. `Authetication: Bearer <token>` with a token Sandstorm generates (preferred).
2. HTTP Basic Auth, with a password Sandstorm generates.

**Comment by rfk** [comment]
Changing the server to support an additional auth mechanism wouldn't be too difficult, as it's fairly modular.  The tricky part would be patching Firefox itself to cooperate.  @julianpistorius if you're interested in taking a run at it, I could point you to the right pieces of code.

**Comment by julianpistorius** [comment]
Thanks @rfk & @kentonv. I am interested. Ryan, where would you recommend starting?

**Comment by rfk** [comment]
If you haven't done already, I'd recommend starting by setting up a self-hosted sync stack outside of sandstorm, to get a sense of the moving pieces:

  https://docs.services.mozilla.com/howtos/run-sync-1.5.html

To work towards sandstorm compatibility, from the server side, there's two layers to authentication in sync.  You'd need to change at least one and maybe both of them.

First, the "tokenserver" takes authentication credentials from Firefox Accounts and returns the user's sync node URL along with some shortlived token credentials:

  http://docs.services.mozilla.com/token/apis.html
  https://github.com/mozilla-services/tokenserver/

So IIUC, you would need to customize the tokenserver to accept sandstorm bearer token auth instead of FxA assertion auth.

In a standard sync setup, Firefox uses the shortlived credentials from tokenserver to auth to the sync storage node.  Depending on the details of how sandstorm works, that may not be possible, and you'd need to also change the auth on the storage node to accept sandstorm bearer tokens.  It uses a pyramid plugin to do auth that you may be able to customize for this purpose:

  https://github.com/mozilla-services/server-syncstorage/blob/master/syncstorage/__init__.py#L15
  https://github.com/mozilla-services/mozservices/blob/master/mozsvc/user/__init__.py

To go along with those server-side changes, you'd need to customize Firefox and replace the way it current does auth.  This would probably get messy because you'd be cutting out a lot of the functionality provided by Firefox Accounts.  The relevant code is largely contained in:

  https://hg.mozilla.org/mozilla-central/file/tip/services/common/tokenserverclient.js

But I'm not sure how hard it will be to change without having to change the code that calls it.

**Comment by kentonv** [comment]
It sounds to me like part 1 is analogous to an "OAuth grant" kind of flow. In an ideal Sandstorm world, this is something Sandstorm itself would provide. Essentially Firefox would make an OAuth request to the Sandstorm server asking for a sync server to use. Sandstorm shows the user the Powerbox UI, the user chooses a sync grain, and then Sandstorm hands back the bearer token (OAuth would call it an "access token"). Then Firefox uses that token whenever performing actual sync operations.

Currently, however, we're not done building the OAuth request flow. Right now, you'll have to do this more manually. One easy built-in way in Sandstorm is to use the webkey icon in the top bar to issue a new token. You'd then need a way to copy/paste that token into Firefox so that it starts syncing with it.

Given my limited understanding, it sounds like it doesn't particularly make sense to port the "tokenserver" to Sandstorm as it replicates functionality that we intend for Sandstorm itself to handle in the future.

**Comment by ar-jan** [comment]
Firefox Sync on Sandstorm would be great, big +1.

**Comment by rfk** [comment]
This hasn't seen any action in a couple of years, so I'm going to close it out.
