### ISSUE TITLE
New warning since last update "fxa.metrics_uid_secret_key is not set"

### ISSUE THREAD

**Issue by rfnx** [mozilla-services/syncserver#76]
Hello,

Since the latest update (commit https://github.com/mozilla-services/syncserver/commit/a727a530d150720aedda656e04e960054b7fdb43) or maybe the one before (https://github.com/mozilla-services/syncserver/commit/aeaa6c1563a2f25c6be91a574745ce31e1844c48), there is a new warning in my log when I start the sync server : 
```
tokenserver - WARNING - fxa.metrics_uid_secret_key is not set. This will allow PII to be more easily identified
```

Do you know how to fix it ?

My configuration : nginx with uwsgi.

**Comment by drmasterblaster** [comment]
Hi

I have the same problem after having installed syncserver on my raspberry pi for the first time. 
`pi@node1:~/syncserver $ make serve
./local/bin/gunicorn --paste ./syncserver.ini
WARNING:tokenserver:fxa.metrics_uid_secret_key is not set. This will allow PII to be more easily identified
`

After that it just freezes and the server never gets startet (have waited 10 minutes for sure). All I can do then is to cancel the process with ^c.


When I run `make test` it returns:

`pi@node1:~/syncserver $ make test
./local/bin/flake8 ./syncserver
./local/bin/nosetests -s syncstorage.tests`

`Ran 281 tests in 250.117s
OK (SKIP=153)`

`Tokenserver tests currently broken due to incorrect file paths
./local/bin/nosetests -s tokenserver.tests
Test against a running server
./local/bin/gunicorn --paste syncserver/tests.ini 2> /dev/null & SERVER_PID=$!; \
sleep 2; \
./local/bin/python -m syncstorage.tests.functional.test_storage \
	--use-token-server http://localhost:5000/token/1.0/sync/1.5; \
kill $SERVER_PID`

`Ran 42 tests in 42.671s
OK (skipped=4)
`

Why does it say: 'Tokenserver tests currently broken due to incorrect file paths'?

Would really appreciate help! Thanks so much in advance!

**Comment by rfk** [comment]
It's safe to ignore this warning - the metrics_uid_secret_key is used to anonymize some metrics data when we run this code in production, but it's probably not very useful to you in a self-hosted setup.

In fact, let's just use a randomly-generated default in order to avoid the warning: https://github.com/mozilla-services/syncserver/commit/c5c7de85d8df870622b97557f6b2450b9fcd880f

**Comment by rfk** [comment]
> After that it just freezes and the server never gets startet (have waited 10 minutes for sure).
> All I can do then is to cancel the process with ^c.

This, I can't explain yet, but I don't think it can possibly be the result of this missing config value.

**Comment by rfk** [comment]
Although I do get errors when trying to do a fresh build...@drmasterblaster would you mind trying a fresh build and, assuming it still fails for you, filing a fresh issue so we can keep track of this issue independently?

**Comment by rfk** [comment]
(I'm going to close this issue out since the warning should no longer appear in the latest version)
