### ISSUE TITLE
No syncing reinstalled device

### ISSUE THREAD

**Issue by Martijn085** [mozilla-services/syncserver#78]
I have running ffsync server for a couple of years now and it work perfectly. I have reinstalled a laptop and have changed the firefox sync password (lost it).

Now firefox doesn`t sync anymore with my own sync server when i logon with the account for this laptop. How can i fix this? Can i change the password or devide ID somewhere in the database?

Hope some can help me out with this one, i can't find anything on the web for this.

**Comment by rfk** [comment]
Hi @Martijn085, can you say more about what you mean by "doesn't sync anymore"?  Do you mean that it's not syncing down the data from before you reinstalled the laptop?

If so, I'm afraid that the data synced by the old laptop is not longer accessible, due to this:

>  changed the firefox sync password (lost it)

When you reset the password on your Firefox Account, it resets the encryption keys and renders any previously-synced data inaccessible.

**Comment by Martijn085** [comment]
Thanks for the reply @rfk! Thats correct, it's not syncing down the data from before the reinstallation of the laptop.

1. Can i reset the encryption keys for this ffsync user in the database?
2. If i can find the old password (before the reset) and restore this password, should everything sync again?

**Comment by rfk** [comment]
No, I'm really sorry, but the password-reset process irreversibly destroys the old encryption keys, I don't think there is any way to get them back.

**Comment by Martijn085** [comment]
Ok, thanks again for the reply. It's clear, I will be better store the passwords in the future.
